#!/bin/bash
# setup-supabase.sh - Script para crear la tabla en Supabase desde terminal

echo "🎯 Script de Configuración - Sistema de Compra"
echo "=============================================="
echo ""
echo "Este script te guiará a través de la configuración de Supabase"
echo ""
echo "⚠️  ANTES DE EJECUTAR:"
echo "1. Crea una cuenta en supabase.com"
echo "2. Crea un nuevo proyecto"
echo "3. Ten a mano tu Project URL y Service Role Key"
echo ""
echo "📋 PASOS:"
echo ""
echo "PASO 1: Ve a https://supabase.com/dashboard"
echo "PASO 2: Abre tu proyecto"
echo "PASO 3: Ve a SQL Editor"
echo "PASO 4: Crea una nueva query"
echo "PASO 5: Copia TODO el contenido de 'setup-database.sql'"
echo "PASO 6: Pega en el SQL Editor y presiona 'RUN'"
echo ""
echo "PASO 7: Ve a Settings → API"
echo "PASO 8: Copia 'Project URL' y 'Service Role Key'"
echo "PASO 9: Abre el archivo .env"
echo "PASO 10: Reemplaza:"
echo "   - PUBLIC_SUPABASE_URL=tu-url"
echo "   - SUPABASE_SERVICE_ROLE_KEY=tu-key"
echo ""
echo "PASO 11: Ejecuta: npm run dev"
echo "PASO 12: Ve a http://localhost:4321/comprar"
echo ""
echo "✅ ¡Listo! El sistema está configurado"
